services:
  php:
    build:
      context: .
      dockerfile: src/docker/Dockerfile
    container_name: php_container
    volumes:
      - ./php:/var/www/html
    ports:
      - "1616:80"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: weather_db
    ports:
      - "1617:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "1618:8080"

volumes:
  db_data:
